# Generated by Django 2.1.8 on 2019-04-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
