# Generated by Django 2.1.8 on 2019-04-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homeForm',
            new_name='homeModel',
        ),
    ]
