# Generated by Django 2.1.8 on 2019-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190523_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illegaldaymodel',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='endTime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='startTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
